import tkinter as tk
from tkinter import messagebox, simpledialog, Menu
import webbrowser
import urllib.parse
import platform
from movie_app_api import MovieApp
import os


class MovieAppTkGui:
    """
    The Tkinter GUI class for the Movie App. It integrates with the MovieApp
    and provides a user interface for managing and viewing movies.
    """
    def __init__(self, root, movie_app):
        """
        Initialize the Tkinter GUI and integrate with the MovieApp.
        
        Args:
            root (tk.Tk): The main Tkinter window.
            movie_app (MovieApp): The instance of the MovieApp class that manages the movies.
        """
        self.root = root
        self.movie_app = movie_app

        # Set window title and dimensions
        self.root.title("Movie App")
        self.root.geometry("600x400")

        # Pagination variables
        self.items_per_page = 5
        self.current_page = 1

        # Create and pack the listbox to display movies
        self.movie_listbox = tk.Listbox(self.root, height=15, width=50)
        self.movie_listbox.pack(pady=20)

        # Create the frame for pagination
        self.pagination_frame = tk.Frame(self.root)
        self.pagination_frame.pack(pady=10)

        # Create a context menu (right-click menu)
        self.create_context_menu()

        # Populate the listbox with movies from the database
        self.populate_movie_list()

        # Bind right-click event for the context menu based on the platform
        if platform.system() == "Darwin":  # macOS
            self.movie_listbox.bind("<Button-2>", self.show_context_menu)
        else:  # Windows/Linux
            self.movie_listbox.bind("<Button-3>", self.show_context_menu)

        # Bind double-click event to open a movie in the browser
        self.movie_listbox.bind("<Double-1>", self.watch_movie)

        # Load more button
        self.load_more_button = tk.Button(self.root, text="Load More", command=self.load_more_movies)
        self.load_more_button.pack()

    def create_context_menu(self):
        """
        Create the right-click context menu.
        
        This method adds various actions to the context menu, such as adding, deleting, 
        searching, and viewing movie statistics, as well as generating the movie website.
        """
        self.context_menu = Menu(self.root, tearoff=0)
        self.context_menu.add_command(label="Add Movie", command=self.add_movie)
        self.context_menu.add_command(label="Delete Movie", command=self.delete_movie)
        self.context_menu.add_command(label="Show Stats", command=self.show_stats)
        self.context_menu.add_command(label="Search Movie", command=self.search_movie)
        self.context_menu.add_command(label="Update Website", command=self.generate_website)
        self.context_menu.add_separator()
        self.context_menu.add_command(label="Exit", command=self.root.quit)

    def show_context_menu(self, event):
        """
        Show the context menu on right-click.
        
        This method is triggered when the user right-clicks on the movie list.
        It displays the context menu at the location of the mouse pointer.
        
        Args:
            event (tk.Event): The event generated by the right-click action.
        """
        try:
            self.context_menu.post(event.x_root, event.y_root)
        except Exception as e:
            print(f"Error showing context menu: {e}")

    def populate_movie_list(self):
        """
        Populate the listbox with movie titles from the database.
        
        This method fetches the list of movie titles from the MovieApp instance and
        populates the Tkinter listbox with these titles. It is called during initialization
        and whenever the movie list is updated.
        """
        self.movie_listbox.delete(0, tk.END)
        movies = self.movie_app._storage.list_movies()
        for movie in movies:
            self.movie_listbox.insert(tk.END, movie)

    def add_movie(self):
        """
        Add new movie to the database and update the list.
        
        This method prompts the user for a movie title via dialog box, attempts to 
        add the movie to the database, and updates the listbox if successful. If the 
        movie could not be added, an error message is shown.
        """
        new_movie = simpledialog.askstring("Add Movie", "Enter movie name:")
        if new_movie:
            success = self.movie_app.add_movie(new_movie) 
            if success:
                self.populate_movie_list()
            else:
                messagebox.showerror("Error", "Movie could not be added.")

    def delete_movie(self):
        """
        Delete a selected movie from the database and update the list.
        
        This method prompts the user to confirm the deletion of a selected movie. If confirmed, 
        the movie is deleted from the database and the listbox is updated.
        """
        selected_movie = self.movie_listbox.get(tk.ACTIVE)
        if selected_movie:
            confirm = messagebox.askyesno("Confirm Delete", f"Are you sure you want to delete '{selected_movie}'?")
            if confirm:
                self.movie_app.delete_movie(selected_movie)
                self.populate_movie_list()
        else:
            messagebox.showerror("Error", "No movie selected!")

    def show_stats(self):
        """
        Display movie statistics in a message box.
        
        This method fetches the movie statistics from the MovieApp instance and 
        displays them in a message box. The statistics may include information such as
        average ratings, best and worst movies, etc.
        """
        stats = self.movie_app.show_stats()
        messagebox.showinfo("Movie Stats", stats)

    def search_movie(self):
        """
        Search for a movie and display the results.
        
        This method prompts the user for a movie title, searches for it in the database
        and displays the search results. If no matching movies are found, an appropriate 
        message is shown.
        """
        search_term = simpledialog.askstring("Search Movie", "Enter movie name:")
        if search_term:
            results = self.movie_app.search_movie(search_term)
            if results:
                result_str = "\n".join(results)
                messagebox.showinfo("Search Results", result_str)
            else:
                messagebox.showinfo("Search Results", "No movies found")

    def generate_website(self):
        """
        Generate the movie website.

        This method triggers the MovieApp instance to generate or update the website 
        that displays the list of movies. Once the website is updated, a message box
        is displayed to inform the user.
        """
        # Extract the user name from the storage file path (similar to main.py)
        user_name = os.path.splitext(os.path.basename(self.movie_app._storage.file_path))[0]
        
        # Generate the HTML filename (e.g., "matthias_index.html")
        html_filename = f"{user_name}_index.html"
        
        # Call the generate_website method and pass the filename
        self.movie_app.generate_website(html_filename)
        
        # Inform the user
        messagebox.showinfo("Website Generated", f"The movie website '{html_filename}' has been updated.")

    def watch_movie(self, event):
        """
        Handle double-click on a movie to watch it.
        
        This method is triggered when the user double-clicks a movie in the listbox.
        It opens the default web browser to the streaming URL for the selected movie.
        
        Args:
            event (tk.Event): The event generated by the double-click action.
        """
        selected = self.movie_listbox.curselection()
        if selected:
            movie_title = self.movie_listbox.get(selected)
            if movie_title:
                # URL encoding the movie title
                query = urllib.parse.quote(movie_title)
                streaming_url = f"https://ww4.123moviesfree.net/search/?q={query}"
                try:
                    webbrowser.open(streaming_url)
                except Exception as e:
                    messagebox.showerror("Error", f"Failed to open browser: {e}")

    def load_more_movies(self):
        """Load more movies and display them."""
        self.current_page += 1
        self.populate_movie_list()

    def create_pagination_buttons(self):
        """Create pagination buttons."""
        # Clear existing pagination buttons
        for widget in self.pagination_frame.winfo_children():
            widget.destroy()

        total_movies = len(self.movie_app._storage.list_movies())
        total_pages = (total_movies // self.items_per_page) + (1 if total_movies % self.items_per_page != 0 else 0)

        if self.current_page > 1:
            prev_button = tk.Button(self.pagination_frame, text="Previous", command=self.prev_page)
            prev_button.grid(row=0, column=0, padx=10)

        if self.current_page < total_pages:
            next_button = tk.Button(self.pagination_frame, text="Next", command=self.next_page)
            next_button.grid(row=0, column=1, padx=10)

    def prev_page(self):
        """Navigate to the previous page."""
        if self.current_page > 1:
            self.current_page -= 1
            self.populate_movie_list()

    def next_page(self):
        """Navigate to the next page."""
        self.current_page += 1
        self.populate_movie_list()

    @staticmethod
    def run_gui(movie_app):
        """
        Run the Movie App GUI.
        
        This static method initializes and runs the Tkinter GUI for the MovieApp.
        
        Args:
            movie_app (MovieApp): The MovieApp instance that provides the movie database.
        """
        root = tk.Tk()
        app_gui = MovieAppTkGui(root, movie_app)
        root.mainloop()
